package main

import (
	"context"
	"fmt"
	"log"
	"log/slog"
	"net/http"
	"os"
	"os/signal"
	"runtime"
	"syscall"
	"time"

	"github.com/okishiro/pidgey/internal/config"
	one "github.com/okishiro/pidgey/internal/http/handlers/hello"
	"github.com/okishiro/pidgey/internal/storage/sqlite"
)

func main() {
	fmt.Println("hello")
	cfg := config.MustLoad()

	database, err := sqlite.New(cfg)
	if err != nil {
		log.Fatal(err)
	}

	slog.Info("storage initialised")

	router := http.NewServeMux()

	router.HandleFunc("POST /movie/{name}", one.CreateMovie(database))
	router.HandleFunc("GET /getdata/{id}", one.GetData(database))
	router.HandleFunc("POST /create/{name}", one.CreateAccount(database, cfg.Storage_path))

	handler := Recovery(
		RequestID(
			RealIP(
				Logger(
					Auth(
						Validator(router),
					),
				),
			),
		),
	)

	server := http.Server{
		Addr:    cfg.HTTPServer.Addr,
		Handler: handler,
	}

	go func() {
		if err := server.ListenAndServe(); err != nil && err != http.ErrServerClosed {
			log.Fatalf("listen error: %v", err)
		}
	}()

	quit := make(chan os.Signal, 1)

	signal.Notify(quit, os.Interrupt, syscall.SIGTERM)

	<-quit
	log.Println("server shutting down")

	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()

	if err := server.Shutdown(ctx); err != nil {
		log.Printf("server forced shut %v", err)
	}
	log.Println("server shut")
}

func Recovery(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		defer func() {
			if err := recover(); err != nil {
				// Get the stack trace (the last 2kb of it)
				trace := make([]byte, 2048)
				runtime.Stack(trace, false)

				// Get the Request ID from the context (Layer 2)
				reqID, _ := r.Context().Value("request_id").(string)

				slog.Error("PANIC RECOVERED",
					"request_id", reqID,
					"err", err,
					"stack", string(trace), // This tells you the line number!
				)

				w.WriteHeader(http.StatusInternalServerError)
			}
		}()
		next.ServeHTTP(w, r)
	})
}

func RequestID(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		id := fmt.Sprintf("req_%d", time.Now().UnixNano())
		w.Header().Set("X-Request-ID", id)
		ctx := context.WithValue(r.Context(), "request_id", id)
		next.ServeHTTP(w, r.WithContext(ctx))
	})
}

func RealIP(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		// Future: parse X-Forwarded-For headers
		next.ServeHTTP(w, r)
	})
}

func Logger(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		start := time.Now()
		id, _ := r.Context().Value("request_id").(string)

		next.ServeHTTP(w, r)

		slog.Info("request processed",
			"id", id,
			"method", r.Method,
			"path", r.URL.Path,
			"duration", time.Since(start),
		)
	})
}

func Auth(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		// Future: Check JWT or Session here
		next.ServeHTTP(w, r)
	})
}

func Validator(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		next.ServeHTTP(w, r)
	})
}

/*

Here is the breakdown of each layer’s purpose in your stack.

1. Recovery

This is your "Bulletproof Vest." If your code tries to access a nil pointer or a database connection that isn't there, Go will "panic" and crash the entire program. Recovery catches that panic, logs the stack trace so you can fix the bug, and sends a 500 error to the user. Without this, one bad request from your stress test could kill the server for everyone.

2. Request ID

This is the "DNA Tag" for every interaction. It generates a unique string (like req_1740...) and attaches it to the request context. Every log line generated by this request will carry this ID. This is the only way to distinguish between different users when your logs are moving at 1,000 lines per second.

3. Real IP

This is the "Identity Verifier" for networking. When you deploy to a cloud provider, the "Remote Address" often shows the IP of the Load Balancer, not the user. This layer looks into special headers like X-Forwarded-For to find the user's actual location. It is essential for security, rate limiting, and blocking malicious actors based on their geography.

4. Logger

This is the "Black Box Recorder." It marks the exact time a request starts and the exact time it finishes. It calculates the Latency (Duration) and logs it alongside the URL and Method. This data is what professional teams use to build dashboards that show if the server is getting slower over time.

5. Auth

This is the "Security Gatekeeper." It inspects the request for a valid JWT token, API key, or session cookie. If the credentials are missing or expired, it returns a 401 Unauthorized immediately. By stopping the request here, you protect your database and business logic from being hit by unauthenticated or malicious traffic.

6. Validator

This is the "Data Bouncer." It checks if the incoming JSON body is actually valid before your handler even touches it. While your handler does specific validation, this layer can do global checks, like ensuring the Content-Length isn't too large (preventing "Giant Payload" attacks). It ensures that only "clean" data reaches the core of your application.

...........................................................

There are two main ways to handle this: trying to store all the reqeusts for observation

1. The "Standard" Way: Structured Log Files

Instead of writing to a database yourself, you write "Structured Logs" (JSON) to a standard text file on the server's disk.

How it works: Your Go app prints JSON to the console (stdout).

The Log Shipper: A separate, lightweight tool (like Filebeat or Promtail) watches that file and "ships" the logs to a central server.

The Central Server: Logs end up in a dedicated system like Elasticsearch (the "E" in ELK stack) or Grafana Loki.

Why this is better: If your database is down, you can still see the logs explaining why it's down.

2. The "Observability" Way: Distributed Tracing

For high-traffic systems, companies use OpenTelemetry (OTEL).

Instead of a text file, the middleware sends a small "packet" of data via UDP or HTTP to a collector (like Jaeger or Honeycomb).

This allows you to see a visual timeline of the request:

0ms: Request Received

10ms: Auth Checked

45ms: SQL Query Finished

50ms: Response Sent

*/
